[TokyoNight]
;https://github.com/enkia/tokyo-night-vscode-theme
accent             = ae5c85
accent-active      = ae5c85
accent-inactive    = 1a1b26
banner             = ae5c85
border-active      = ae5c85
border-inactive    = 24283b
header             = 565f89
highlight          = 24283b
main               = 070606
notification       = 7aa2f7
notification-error = f7768e
subtext            = 565f89
text               = a9b1d6
